name: Reroute
description: Simple Redirect Server for lcoal host and short links
url: 'https://reroute.work'
baseurl: '/'
email: jinfo@reroute.work
twitter: https://twitter.com/
youtube: https://www.youtube.com/
facebook: https://www.facebook.com/
google_analytics: ''

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video
